### ISSUE TITLE
Clarification on Adding Visual Indicators (Loading Circle or Skeleton Text)

### ISSUE THREAD

**Issue by Adhithya03** [Ryan526/Thinking#1]
Hello @Ryan526 ,

Thank you for the great work on this project! I have a question about the function implementation. After reviewing the code, I couldn't find any visual indicators, such as a loading circle or skeleton text, "thinking" state during execution.

Could you kindly clarify if this functionality is handled elsewhere or if there’s a recommended approach to add such indicators? I am trying to learn this stuff and contribute like you did.

Thank you for your assistance!

**Comment by Ryan526** [comment]
@Adhithya03 I'm not really a coder. I went back and forth with 4o until it came up with a working script. I believe those elements are imported from pydantic at the start of the script.

I used a couple existing Filter and Pipe functions on openwebui to use as examples and context for it to understand what I was trying to do.

**Comment by Adhithya03** [comment]
Sounds like a 'me' story, haha! I used _your script_ as reference and with GPT-4o I made a filter for an OCR (Optical Character Recognition) bot for transcribing images.

### **While Transcribing**  
![image](https://github.com/user-attachments/assets/97eed308-3ded-4cde-b35a-73f193d561ef)  

### **After Processing**  
![image](https://github.com/user-attachments/assets/95c5a2e8-d5a0-4152-ab42-ef47cd4fe451)  


Anyway Thanks, it was nice talking to you! 😄
